name: Sample Required Workflow

on: 
  pull_request:
    branches: [main]

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        run: echo "This is a required workflow" >> $GITHUB_STEP_SUMMARY
        
